### ISSUE TITLE
No dsgvo.css loaded on plain Plone 5.2.1

### ISSUE THREAD

**Issue by andreasma** [kitconcept/kitconcept.dsgvo#12]
I created a new Plone buildout using Python 3.6 and Plone 5.2.1 with kitconpept 1.1 and the dsgvo-banner displays in the top part of the site. I looked via webdeveloper - inspector into the source of the rendered website and there seemed no dsgvo.css loaded.
I checked also via Resource Registries and Configuration Registry of the site, if there is a dsgvo.css listed. But it is not.

**Comment by tisto** [comment]
@andreasma could you attach a screenshot (ideally with the dev toolbar where I can see the failed request)? Maybe the resource registry changed somehow in Plone 5.2.1.

**Comment by andreasma** [comment]
![kitconcept_dsgvo_plone_521_python_36](https://user-images.githubusercontent.com/725590/75155915-4ca28000-5711-11ea-90da-1a6a76ff8184.png)
A Screenshot from Home of a new Plone 5.2.1 site.

And here a Screenshot from the developer tools - inspector - sources:
![kitconcept_dsgvo_plone_521_python_36_inspector_sources](https://user-images.githubusercontent.com/725590/75156327-30eba980-5712-11ea-8e28-7313e01793f0.png)

HTH

**Comment by andreasma** [comment]
Maybe this PLIP is getting into the way?:
https://github.com/plone/Products.CMFPlone/issues/1742

Remove support for old style resource registries
For Developers
Support for old-style resource registries (cssregistry.xml and jsregistry.xml) was removed completely along with the tools portal_css or portal_javascript.
You need to add resources using the new Resource Registry. See resources for detailed instructions.
https://docs.plone.org/adapt-and-extend/theming/resourceregistry.html#resource-registry-resources

**Comment by tisto** [comment]
@andreasma fixed and released with https://pypi.org/project/kitconcept.dsgvo/1.1.1/#id1. You might have to re-install the add-on.
